name: Generate contribution snake

on:
  schedule:
    - cron: "0 2 * * *"   # Daily at 02:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main              # Change to 'master' if your repo uses master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (dark & light)
        uses: Platane/snk@v3
        with:
          github_user_name: ralsina
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?palette=github-light

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
